apiVersion: apps/v1
kind: Deployment
metadata:
  name: binance-websocket
  labels:
    app: binance-websocket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: binance-websocket
  template:
    metadata:
      labels:
        app: binance-websocket
    spec:
      containers:
        - name: binance-websocket
          image: binance-websocket:latest
          imagePullPolicy: Never